---
- name: Set SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  nsible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable IPtables
  nsible.builtin.command: iptables -F