---
- name: Gather facts
  ansible.builtin.setup:

- name: Install Docker (for YUM-based environment)
  ansible.builtin.yum:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  notify: Restart Docker service
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Docker (for APT-based environment)
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  notify: Restart Docker service
  when: ansible_facts['os_family'] == 'Debian'