name: Ansible Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Set up SSH key
      run: |
        sudo mkdir -p /keys
        echo "${{ secrets.ssh_key }}" | sudo tee /keys/k8s-nginx.pem > /dev/null
        sudo chmod 600 /keys/k8s-nginx.pem

    - name: Run Ansible playbook
      env:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      run: |
        ansible-playbook ./playbooks/main.yml --private-key=/keys/k8s-nginx.pem
